### ISSUE TITLE
Could you please update the pkg for macOS 13.3 beta 2

### ISSUE THREAD

**Issue by gspannu** [scr34m/MailDisableAutoRead#1]
I think the PluginCompatibilityUUID value for macOS 13.3 beta 2 onwards ha been changed.

**Could you please update your package to support the same?**

Attached mail info.plist from macOS 13.3 beta2 (if it helps)
[Info.plist.log](https://github.com/scr34m/MailDisableAutoRead/files/10893099/Info.plist.log)
{Renamed to .log for uploading}

Or you may refer to the updated PluginCompatibilityUUID values from another mail-plugin here.
https://github.com/apparition47/MailTrackerBlocker/blob/main/Resources/Info.plist

**Comment by scr34m** [comment]
I've not using the beta builds, but i will do it with the linked information.

**Comment by scr34m** [comment]
Here it is [MailDisableAutoRead.pkg.zip](https://github.com/scr34m/MailDisableAutoRead/files/10895288/MailDisableAutoRead.pkg.zip)

**Comment by gspannu** [comment]
> Here it is [MailDisableAutoRead.pkg.zip](https://github.com/scr34m/MailDisableAutoRead/files/10895288/MailDisableAutoRead.pkg.zip)

Thank you.
I will test it in the evening (on my dev machine, running macOS 13.3 beta) and confirm...

**Comment by gspannu** [comment]
> Here it is [MailDisableAutoRead.pkg.zip](https://github.com/scr34m/MailDisableAutoRead/files/10895288/MailDisableAutoRead.pkg.zip)

Installed and tested on macOS 13.3 beta2, works out of the box. 👍 

I still encounter the bug (as mentioned [here](https://github.com/scr34m/MailDisableAutoRead/issues/2)) on both my machines.
It doesn't happen every time...
